Name:           ros-indigo-agile-grasp
Version:        0.7.0
Release:        0%{?dist}
Summary:        ROS agile_grasp package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/agile_grasp
Source0:        %{name}-%{version}.tar.gz

Requires:       lapack-devel
Requires:       pcl
Requires:       pcl-tools
Requires:       ros-indigo-cmake-modules
Requires:       ros-indigo-cv-bridge
Requires:       ros-indigo-eigen-conversions
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-pcl-conversions
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-std-msgs
BuildRequires:  lapack-devel
BuildRequires:  pcl-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-cv-bridge
BuildRequires:  ros-indigo-eigen-conversions
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-pcl-conversions
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-std-msgs

%description
The agile_grasp ROS package. AGILE stands for Antipodal Grasp Identification and
LEarning. The package finds antipodal grasps in point clouds.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed May 13 2015 Andreas ten Pas <atp@ccs.neu.edu> - 0.7.0-0
- Autogenerated by Bloom

* Sat Apr 11 2015 Andreas ten Pas <atp@ccs.neu.edu> - 0.6.2-0
- Autogenerated by Bloom

* Fri Apr 10 2015 Andreas ten Pas <atp@ccs.neu.edu> - 0.6.1-3
- Autogenerated by Bloom

* Fri Apr 10 2015 Andreas ten Pas <atp@ccs.neu.edu> - 0.6.1-2
- Autogenerated by Bloom

* Fri Apr 10 2015 Andreas ten Pas <atp@ccs.neu.edu> - 0.6.1-1
- Autogenerated by Bloom

* Fri Apr 10 2015 Andreas ten Pas <atp@ccs.neu.edu> - 0.6.1-0
- Autogenerated by Bloom

